// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _do_macc_macc_HH_
#define _do_macc_macc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "do_macc_fadd_32ns_32ns_32_5_full_dsp.h"
#include "do_macc_fmul_32ns_32ns_32_4_max_dsp.h"

namespace ap_rtl {

struct do_macc_macc : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > img_in_address0;
    sc_out< sc_logic > img_in_ce0;
    sc_in< sc_lv<32> > img_in_q0;
    sc_out< sc_lv<4> > img_in_address1;
    sc_out< sc_logic > img_in_ce1;
    sc_in< sc_lv<32> > img_in_q1;
    sc_out< sc_lv<4> > filt_in_address0;
    sc_out< sc_logic > filt_in_ce0;
    sc_in< sc_lv<32> > filt_in_q0;
    sc_out< sc_lv<4> > filt_in_address1;
    sc_out< sc_logic > filt_in_ce1;
    sc_in< sc_lv<32> > filt_in_q1;
    sc_out< sc_lv<4> > prod_out_address0;
    sc_out< sc_logic > prod_out_ce0;
    sc_out< sc_logic > prod_out_we0;
    sc_out< sc_lv<32> > prod_out_d0;
    sc_out< sc_lv<4> > prod_out_address1;
    sc_out< sc_logic > prod_out_ce1;
    sc_out< sc_logic > prod_out_we1;
    sc_out< sc_lv<32> > prod_out_d1;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    do_macc_macc(sc_module_name name);
    SC_HAS_PROCESS(do_macc_macc);

    ~do_macc_macc();

    sc_trace_file* mVcdFile;

    do_macc_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* do_macc_fadd_32ns_32ns_32_5_full_dsp_U1;
    do_macc_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* do_macc_fadd_32ns_32ns_32_5_full_dsp_U2;
    do_macc_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>* do_macc_fmul_32ns_32ns_32_4_max_dsp_U3;
    do_macc_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>* do_macc_fmul_32ns_32ns_32_4_max_dsp_U4;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it7;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it8;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it9;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it10;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg4_fsm_4;
    sc_signal< bool > ap_sig_bdd_79;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg1_fsm_1;
    sc_signal< bool > ap_sig_bdd_130;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg2_fsm_2;
    sc_signal< bool > ap_sig_bdd_150;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg3_fsm_3;
    sc_signal< bool > ap_sig_bdd_170;
    sc_signal< sc_lv<32> > grp_fu_307_p2;
    sc_signal< sc_lv<32> > processing_element_products_reg_463;
    sc_signal< sc_lv<32> > grp_fu_314_p2;
    sc_signal< sc_lv<32> > processing_element_products_1_s_reg_468;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1;
    sc_signal< sc_lv<32> > processing_element_products_2_s_reg_503;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3;
    sc_signal< sc_lv<32> > processing_element_products_3_s_reg_508;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4;
    sc_signal< sc_lv<32> > processing_element_products_4_s_reg_523;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5;
    sc_signal< sc_lv<32> > processing_element_products_5_s_reg_528;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6;
    sc_signal< sc_lv<32> > processing_element_products_6_s_reg_533;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7;
    sc_signal< sc_lv<32> > processing_element_products_7_s_reg_538;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8;
    sc_signal< sc_lv<32> > processing_element_products_8_s_reg_543;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8;
    sc_signal< sc_lv<32> > ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9;
    sc_signal< sc_lv<32> > grp_fu_298_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_548;
    sc_signal< sc_lv<32> > grp_fu_303_p2;
    sc_signal< sc_lv<32> > tmp_5_1_reg_553;
    sc_signal< sc_lv<32> > tmp_5_2_reg_558;
    sc_signal< sc_lv<32> > tmp_5_3_reg_563;
    sc_signal< sc_lv<32> > tmp_5_4_reg_568;
    sc_signal< sc_lv<32> > tmp_5_5_reg_573;
    sc_signal< sc_lv<32> > tmp_5_6_reg_578;
    sc_signal< sc_lv<32> > tmp_5_7_reg_583;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0_preg;
    sc_signal< sc_lv<32> > grp_fu_298_p0;
    sc_signal< sc_lv<32> > grp_fu_298_p1;
    sc_signal< sc_lv<32> > grp_fu_303_p0;
    sc_signal< sc_lv<32> > grp_fu_303_p1;
    sc_signal< sc_logic > grp_fu_298_ce;
    sc_signal< sc_logic > grp_fu_303_ce;
    sc_signal< sc_logic > grp_fu_307_ce;
    sc_signal< sc_logic > grp_fu_314_ce;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< sc_logic > ap_sig_pprstidle_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_pp0_stg0_fsm_0;
    static const sc_lv<5> ap_ST_pp0_stg1_fsm_1;
    static const sc_lv<5> ap_ST_pp0_stg2_fsm_2;
    static const sc_lv<5> ap_ST_pp0_stg3_fsm_3;
    static const sc_lv<5> ap_ST_pp0_stg4_fsm_4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<64> ap_const_lv64_8;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_reg_ppiten_pp0_it0();
    void thread_ap_return();
    void thread_ap_sig_bdd_130();
    void thread_ap_sig_bdd_150();
    void thread_ap_sig_bdd_170();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_79();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_0();
    void thread_ap_sig_cseq_ST_pp0_stg1_fsm_1();
    void thread_ap_sig_cseq_ST_pp0_stg2_fsm_2();
    void thread_ap_sig_cseq_ST_pp0_stg3_fsm_3();
    void thread_ap_sig_cseq_ST_pp0_stg4_fsm_4();
    void thread_ap_sig_pprstidle_pp0();
    void thread_filt_in_address0();
    void thread_filt_in_address1();
    void thread_filt_in_ce0();
    void thread_filt_in_ce1();
    void thread_grp_fu_298_ce();
    void thread_grp_fu_298_p0();
    void thread_grp_fu_298_p1();
    void thread_grp_fu_303_ce();
    void thread_grp_fu_303_p0();
    void thread_grp_fu_303_p1();
    void thread_grp_fu_307_ce();
    void thread_grp_fu_314_ce();
    void thread_img_in_address0();
    void thread_img_in_address1();
    void thread_img_in_ce0();
    void thread_img_in_ce1();
    void thread_prod_out_address0();
    void thread_prod_out_address1();
    void thread_prod_out_ce0();
    void thread_prod_out_ce1();
    void thread_prod_out_d0();
    void thread_prod_out_d1();
    void thread_prod_out_we0();
    void thread_prod_out_we1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
