
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from miniFire.prototxt and miniFire.caffemodel
// (c) 2016 David Gschwend
///////

#ifndef _NETWORK_H_
#define _NETWORK_H_

#include "netconfig.hpp"

const int MAX_NUM_LAYERS = 7;
const int MAX_WEIGHTS_PER_LAYER = 224;
const int MAX_IMAGE_CACHE_SIZE = 192;
const int MAX_NUM_CHOUT = 10;
//const int MAX_ACTIVE_AREA_SIZE = 160;

network_t *get_network_config();

#endif
