
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from miniFire.prototxt and miniFire.caffemodel
// (c) 2016 David Gschwend
///////

#include "miniFire.hpp"

network_t *get_network_config() {
  network_t *net = new network_t(7, 420);

  // Layer Attributes: (NAME    , TYPE      ,   W,   H,  CI,  CO, K, P, S) EXP UPDMEM?
  addLayer(net, layer_t("data  ", LAYER_DATA,   0,   0,   0,   3, 0, 0, 0), 0, 0);
  addLayer(net, layer_t("conv1 ", LAYER_CONV,   8,   8,   3,   8, 3, 1, 2), 0, 1);
  addLayer(net, layer_t("f/s1  ", LAYER_CONV,   4,   4,   8,   2, 1, 0, 1), 0, 1);
  addLayer(net, layer_t("f/e1  ", LAYER_CONV,   4,   4,   2,   4, 1, 0, 1), 1, 1);
  addLayer(net, layer_t("f/e3  ", LAYER_CONV,   4,   4,   2,   4, 3, 1, 1), 1, 0);
  addLayer(net, layer_t("conv10", LAYER_CONV,   4,   4,   8,  10, 1, 0, 1), 0, 1);
  addLayer(net, layer_t("pool10", LAYER_POOL,   4,   4,  10,  10, 4, 0, 4), 0, 1);

  net->num_weights = 420;
  char* filename = "miniFire.bin";
  loadWeightsFromFile(net, filename);

  return net;
}
