
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and snapshot_iter_140140.caffemodel
// (c) 2016 David Gschwend
///////

#ifndef _NETWORK_H_
#define _NETWORK_H_

#include "netconfig.hpp"

const int MAX_NUM_LAYERS = 26;
const int MAX_WEIGHTS_PER_LAYER = 513000;
const int MAX_IMAGE_CACHE_SIZE = 524288;
const int MAX_NUM_CHOUT = 1000;
//const int MAX_ACTIVE_AREA_SIZE = 576;

network_t *get_network_config();

#endif
