
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and snapshot_iter_140140.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"

network_t *get_network_config() {
  network_t *net = new network_t(30, 1405768);

  //                                                                           UPD GLBL
  // Layer Attributes: (NAME    , TYPE      ,   W,   H,  CI,  CO, K, P, S) EXP MEM POOL?
  addLayer(net, layer_t("conv1 ", LAYER_CONV, 256, 256,   3,  64, 3, 1, 2), 0, 1, 0);
  addLayer(net, layer_t("pool1 ", LAYER_POOL, 128, 128,  64,  64, 3, 0, 2), 0, 1, 0);
  addLayer(net, layer_t("f2/s1 ", LAYER_CONV,  64,  64,  64,  16, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f2/e1 ", LAYER_CONV,  64,  64,  16,  64, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f2/e3 ", LAYER_CONV,  64,  64,  16,  64, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("f3/s1 ", LAYER_CONV,  64,  64, 128,  16, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f3/e1 ", LAYER_CONV,  64,  64,  16,  64, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f3/e3 ", LAYER_CONV,  64,  64,  16,  64, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("pool3 ", LAYER_POOL,  64,  64, 128, 128, 3, 0, 2), 0, 1, 0);
  addLayer(net, layer_t("f4/s1 ", LAYER_CONV,  32,  32, 128,  32, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f4/e1 ", LAYER_CONV,  32,  32,  32, 128, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f4/e3 ", LAYER_CONV,  32,  32,  32, 128, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("f5/s1 ", LAYER_CONV,  32,  32, 256,  32, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f5/e1 ", LAYER_CONV,  32,  32,  32, 128, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f5/e3 ", LAYER_CONV,  32,  32,  32, 128, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("pool5 ", LAYER_POOL,  32,  32, 256, 256, 3, 0, 2), 0, 1, 0);
  addLayer(net, layer_t("f6/s1 ", LAYER_CONV,  16,  16, 256,  64, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f6/e1 ", LAYER_CONV,  16,  16,  64, 256, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f6/e3 ", LAYER_CONV,  16,  16,  64, 256, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("f7/s1 ", LAYER_CONV,  16,  16, 512,  64, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f7/e1 ", LAYER_CONV,  16,  16,  64, 256, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f7/e3 ", LAYER_CONV,  16,  16,  64, 256, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("f8/s1 ", LAYER_CONV,  16,  16, 512,  64, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f8/e1 ", LAYER_CONV,  16,  16,  64, 256, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f8/e3 ", LAYER_CONV,  16,  16,  64, 256, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("f9/s1 ", LAYER_CONV,  16,  16, 512,  64, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("f9/e1 ", LAYER_CONV,  16,  16,  64, 256, 1, 0, 1), 1, 1, 0);
  addLayer(net, layer_t("f9/e3 ", LAYER_CONV,  16,  16,  64, 256, 3, 1, 1), 1, 0, 0);
  addLayer(net, layer_t("conv10", LAYER_CONV,  16,  16, 512,1000, 1, 0, 1), 0, 1, 0);
  addLayer(net, layer_t("pool10", LAYER_POOL,  16,  16,1000,1000,16, 0,16), 0, 1, 1);

  net->num_weights = 1405768;
  char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);

  return net;
}
