
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and modified.caffemodel
// (c) 2016 David Gschwend
///////

#ifndef _NETWORK_H_
#define _NETWORK_H_

#include "netconfig.hpp"

// Size Limits for this Network
const int MAX_NUM_LAYERS = 5;
const int MAX_WEIGHTS_PER_LAYER = 224;
const int MAX_IMAGE_CACHE_SIZE = 192;
const int MAX_NUM_CHOUT = 10;

// Mean Pixel for ImageNet Data
const float MEAN_R = 104;
const float MEAN_G = 117;
const float MEAN_B = 123;

network_t *get_network_config();

#endif
