// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module do_macc_macc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_address0,
        img_in_ce0,
        img_in_q0,
        img_in_address1,
        img_in_ce1,
        img_in_q1,
        filt_in_address0,
        filt_in_ce0,
        filt_in_q0,
        filt_in_address1,
        filt_in_ce1,
        filt_in_q1,
        prod_out_address0,
        prod_out_ce0,
        prod_out_we0,
        prod_out_d0,
        prod_out_address1,
        prod_out_ce1,
        prod_out_we1,
        prod_out_d1,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_pp0_stg0_fsm_0 = 5'b1;
parameter    ap_ST_pp0_stg1_fsm_1 = 5'b10;
parameter    ap_ST_pp0_stg2_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg3_fsm_3 = 5'b1000;
parameter    ap_ST_pp0_stg4_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv64_2 = 64'b10;
parameter    ap_const_lv64_3 = 64'b11;
parameter    ap_const_lv64_4 = 64'b100;
parameter    ap_const_lv64_5 = 64'b101;
parameter    ap_const_lv64_6 = 64'b110;
parameter    ap_const_lv64_7 = 64'b111;
parameter    ap_const_lv64_8 = 64'b1000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] img_in_address0;
output   img_in_ce0;
input  [31:0] img_in_q0;
output  [3:0] img_in_address1;
output   img_in_ce1;
input  [31:0] img_in_q1;
output  [3:0] filt_in_address0;
output   filt_in_ce0;
input  [31:0] filt_in_q0;
output  [3:0] filt_in_address1;
output   filt_in_ce1;
input  [31:0] filt_in_q1;
output  [3:0] prod_out_address0;
output   prod_out_ce0;
output   prod_out_we0;
output  [31:0] prod_out_d0;
output  [3:0] prod_out_address1;
output   prod_out_ce1;
output   prod_out_we1;
output  [31:0] prod_out_d1;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] img_in_address0;
reg img_in_ce0;
reg[3:0] img_in_address1;
reg img_in_ce1;
reg[3:0] filt_in_address0;
reg filt_in_ce0;
reg[3:0] filt_in_address1;
reg filt_in_ce1;
reg[3:0] prod_out_address0;
reg prod_out_ce0;
reg prod_out_we0;
reg[31:0] prod_out_d0;
reg[3:0] prod_out_address1;
reg prod_out_ce1;
reg prod_out_we1;
reg[31:0] prod_out_d1;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_bdd_23;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_4;
reg    ap_sig_bdd_79;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_1;
reg    ap_sig_bdd_130;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_2;
reg    ap_sig_bdd_150;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_3;
reg    ap_sig_bdd_170;
wire   [31:0] grp_fu_307_p2;
reg   [31:0] processing_element_products_reg_463;
wire   [31:0] grp_fu_314_p2;
reg   [31:0] processing_element_products_1_s_reg_468;
reg   [31:0] ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1;
reg   [31:0] processing_element_products_2_s_reg_503;
reg   [31:0] ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3;
reg   [31:0] processing_element_products_3_s_reg_508;
reg   [31:0] ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4;
reg   [31:0] processing_element_products_4_s_reg_523;
reg   [31:0] ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4;
reg   [31:0] ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5;
reg   [31:0] processing_element_products_5_s_reg_528;
reg   [31:0] ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4;
reg   [31:0] ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5;
reg   [31:0] ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6;
reg   [31:0] processing_element_products_6_s_reg_533;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6;
reg   [31:0] ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7;
reg   [31:0] processing_element_products_7_s_reg_538;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7;
reg   [31:0] ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8;
reg   [31:0] processing_element_products_8_s_reg_543;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8;
reg   [31:0] ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9;
wire   [31:0] grp_fu_298_p2;
reg   [31:0] tmp_s_reg_548;
wire   [31:0] grp_fu_303_p2;
reg   [31:0] tmp_5_1_reg_553;
reg   [31:0] tmp_5_2_reg_558;
reg   [31:0] tmp_5_3_reg_563;
reg   [31:0] tmp_5_4_reg_568;
reg   [31:0] tmp_5_5_reg_573;
reg   [31:0] tmp_5_6_reg_578;
reg   [31:0] tmp_5_7_reg_583;
reg    ap_reg_ppiten_pp0_it0_preg = 1'b0;
reg   [31:0] grp_fu_298_p0;
reg   [31:0] grp_fu_298_p1;
reg   [31:0] grp_fu_303_p0;
reg   [31:0] grp_fu_303_p1;
wire    grp_fu_298_ce;
wire    grp_fu_303_ce;
wire    grp_fu_307_ce;
wire    grp_fu_314_ce;
reg   [4:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;


do_macc_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
do_macc_fadd_32ns_32ns_32_5_full_dsp_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_298_p0 ),
    .din1( grp_fu_298_p1 ),
    .ce( grp_fu_298_ce ),
    .dout( grp_fu_298_p2 )
);

do_macc_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
do_macc_fadd_32ns_32ns_32_5_full_dsp_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_303_p0 ),
    .din1( grp_fu_303_p1 ),
    .ce( grp_fu_303_ce ),
    .dout( grp_fu_303_p2 )
);

do_macc_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
do_macc_fmul_32ns_32ns_32_4_max_dsp_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( img_in_q0 ),
    .din1( filt_in_q0 ),
    .ce( grp_fu_307_ce ),
    .dout( grp_fu_307_p2 )
);

do_macc_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
do_macc_fmul_32ns_32ns_32_4_max_dsp_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( img_in_q1 ),
    .din1( filt_in_q1 ),
    .ce( grp_fu_314_ce ),
    .dout( grp_fu_314_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0_preg
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0_preg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)))) begin
            ap_reg_ppiten_pp0_it0_preg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) begin
            ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
        ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1 <= processing_element_products_1_s_reg_468;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)))) begin
        ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2 <= processing_element_products_2_s_reg_503;
        ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3 <= ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2;
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2 <= processing_element_products_3_s_reg_508;
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3 <= ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2;
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4 <= ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2 <= processing_element_products_4_s_reg_523;
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3 <= ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2;
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4 <= ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3;
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5 <= ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4;
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2 <= processing_element_products_5_s_reg_528;
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3 <= ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2;
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4 <= ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3;
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5 <= ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4;
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6 <= ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2 <= processing_element_products_6_s_reg_533;
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3 <= ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2;
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4 <= ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3;
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5 <= ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4;
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6 <= ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5;
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7 <= ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2 <= processing_element_products_7_s_reg_538;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6;
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8 <= ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2 <= processing_element_products_8_s_reg_543;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7;
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9 <= ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        processing_element_products_1_s_reg_468 <= grp_fu_314_p2;
        processing_element_products_reg_463 <= grp_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)))) begin
        processing_element_products_2_s_reg_503 <= grp_fu_307_p2;
        processing_element_products_3_s_reg_508 <= grp_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        processing_element_products_4_s_reg_523 <= grp_fu_307_p2;
        processing_element_products_5_s_reg_528 <= grp_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        processing_element_products_6_s_reg_533 <= grp_fu_307_p2;
        processing_element_products_7_s_reg_538 <= grp_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        processing_element_products_8_s_reg_543 <= grp_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        tmp_5_1_reg_553 <= grp_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)))) begin
        tmp_5_2_reg_558 <= grp_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)))) begin
        tmp_5_3_reg_563 <= grp_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        tmp_5_4_reg_568 <= grp_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        tmp_5_5_reg_573 <= grp_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        tmp_5_6_reg_578 <= grp_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        tmp_5_7_reg_583 <= grp_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        tmp_s_reg_548 <= grp_fu_298_p2;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it10 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it10) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it7 or ap_reg_ppiten_pp0_it8 or ap_reg_ppiten_pp0_it9 or ap_reg_ppiten_pp0_it10) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it2) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it3) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it4) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it10))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg4_fsm_4) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0_preg) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
        ap_reg_ppiten_pp0_it0 = ap_start;
    end else begin
        ap_reg_ppiten_pp0_it0 = ap_reg_ppiten_pp0_it0_preg;
    end
end

always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_130) begin
    if (ap_sig_bdd_130) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_150) begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_170) begin
    if (ap_sig_bdd_170) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_79) begin
    if (ap_sig_bdd_79) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it7 or ap_reg_ppiten_pp0_it8 or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_0 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it2) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it3) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it4) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_0 == ap_start))) begin
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    end else begin
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            filt_in_address0 = ap_const_lv64_8;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            filt_in_address0 = ap_const_lv64_6;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            filt_in_address0 = ap_const_lv64_4;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            filt_in_address0 = ap_const_lv64_2;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            filt_in_address0 = ap_const_lv64_0;
        end else begin
            filt_in_address0 = 'bx;
        end
    end else begin
        filt_in_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            filt_in_address1 = ap_const_lv64_7;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            filt_in_address1 = ap_const_lv64_5;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            filt_in_address1 = ap_const_lv64_3;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            filt_in_address1 = ap_const_lv64_1;
        end else begin
            filt_in_address1 = 'bx;
        end
    end else begin
        filt_in_address1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))))) begin
        filt_in_ce0 = ap_const_logic_1;
    end else begin
        filt_in_ce0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))))) begin
        filt_in_ce1 = ap_const_logic_1;
    end else begin
        filt_in_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it7 or ap_reg_ppiten_pp0_it9 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3 or processing_element_products_reg_463 or tmp_5_1_reg_553 or tmp_5_3_reg_563 or tmp_5_5_reg_573 or tmp_5_7_reg_583) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        grp_fu_298_p0 = tmp_5_7_reg_583;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        grp_fu_298_p0 = tmp_5_5_reg_573;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        grp_fu_298_p0 = tmp_5_3_reg_563;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        grp_fu_298_p0 = tmp_5_1_reg_553;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        grp_fu_298_p0 = processing_element_products_reg_463;
    end else begin
        grp_fu_298_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it7 or ap_reg_ppiten_pp0_it9 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3 or ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3 or ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5 or ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7 or ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        grp_fu_298_p1 = ap_const_lv32_0;
    end else begin
        grp_fu_298_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it8 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3 or tmp_s_reg_548 or tmp_5_2_reg_558 or tmp_5_4_reg_568 or tmp_5_6_reg_578) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        grp_fu_303_p0 = tmp_5_6_reg_578;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        grp_fu_303_p0 = tmp_5_4_reg_568;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        grp_fu_303_p0 = tmp_5_2_reg_558;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        grp_fu_303_p0 = tmp_s_reg_548;
    end else begin
        grp_fu_303_p0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it8 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3 or ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1 or ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4 or ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6 or ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1;
    end else begin
        grp_fu_303_p1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            img_in_address0 = ap_const_lv64_8;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            img_in_address0 = ap_const_lv64_6;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            img_in_address0 = ap_const_lv64_4;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            img_in_address0 = ap_const_lv64_2;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            img_in_address0 = ap_const_lv64_0;
        end else begin
            img_in_address0 = 'bx;
        end
    end else begin
        img_in_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            img_in_address1 = ap_const_lv64_7;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            img_in_address1 = ap_const_lv64_5;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            img_in_address1 = ap_const_lv64_3;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            img_in_address1 = ap_const_lv64_1;
        end else begin
            img_in_address1 = 'bx;
        end
    end else begin
        img_in_address1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))))) begin
        img_in_ce0 = ap_const_logic_1;
    end else begin
        img_in_ce0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))))) begin
        img_in_ce1 = ap_const_logic_1;
    end else begin
        img_in_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3))) begin
        prod_out_address0 = ap_const_lv64_8;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        prod_out_address0 = ap_const_lv64_6;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        prod_out_address0 = ap_const_lv64_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        prod_out_address0 = ap_const_lv64_2;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        prod_out_address0 = ap_const_lv64_1;
    end else begin
        prod_out_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        prod_out_address1 = ap_const_lv64_7;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        prod_out_address1 = ap_const_lv64_5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        prod_out_address1 = ap_const_lv64_3;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        prod_out_address1 = ap_const_lv64_0;
    end else begin
        prod_out_address1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)))) begin
        prod_out_ce0 = ap_const_logic_1;
    end else begin
        prod_out_ce0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)))) begin
        prod_out_ce1 = ap_const_logic_1;
    end else begin
        prod_out_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3 or grp_fu_307_p2 or grp_fu_314_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)))) begin
        prod_out_d0 = grp_fu_307_p2;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        prod_out_d0 = grp_fu_314_p2;
    end else begin
        prod_out_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or grp_fu_307_p2 or grp_fu_314_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)))) begin
        prod_out_d1 = grp_fu_314_p2;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        prod_out_d1 = grp_fu_307_p2;
    end else begin
        prod_out_d1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2 or ap_sig_cseq_ST_pp0_stg3_fsm_3) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)))) begin
        prod_out_we0 = ap_const_logic_1;
    end else begin
        prod_out_we0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_pp0_stg0_fsm_0 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_sig_cseq_ST_pp0_stg4_fsm_4 or ap_sig_cseq_ST_pp0_stg1_fsm_1 or ap_sig_cseq_ST_pp0_stg2_fsm_2) begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0))) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)))) begin
        prod_out_we1 = ap_const_logic_1;
    end else begin
        prod_out_we1 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it7 or ap_reg_ppiten_pp0_it8 or ap_reg_ppiten_pp0_it9 or ap_reg_ppiten_pp0_it10 or ap_sig_pprstidle_pp0) begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (ap_start == ap_const_logic_0)) & ~((ap_const_logic_0 == ap_reg_ppiten_pp0_it1) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it2) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it3) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it4) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it5) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it6) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it7) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it8) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it9) & (ap_const_logic_0 == ap_reg_ppiten_pp0_it10) & (ap_const_logic_0 == ap_start)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            end
        end
        ap_ST_pp0_stg1_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_2;
        end
        ap_ST_pp0_stg2_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_3;
        end
        ap_ST_pp0_stg3_fsm_3 : 
        begin
            if (~(ap_const_logic_1 == ap_sig_pprstidle_pp0)) begin
                ap_NS_fsm = ap_ST_pp0_stg4_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            end
        end
        ap_ST_pp0_stg4_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_return = grp_fu_298_p2;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_130 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_170 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_79 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign grp_fu_298_ce = ap_const_logic_1;

assign grp_fu_303_ce = ap_const_logic_1;

assign grp_fu_307_ce = ap_const_logic_1;

assign grp_fu_314_ce = ap_const_logic_1;


endmodule //do_macc_macc

