
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and modified.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"
network_t *get_network_config() {
  network_t *net = new network_t(5, 3448);

  //                                                                            UPD
  // Layer Attributes: ( NAME   , TYPE      ,   W,   H,   CI,  CO, K, P, S) EXP MEM POOL Type
  addLayer(net, layer_t("conv1 ", LAYER_CONV,  16,  16,    3,  16, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f2/s1 ", LAYER_CONV,   8,   8,   16,   8, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f2/e1 ", LAYER_CONV,   4,   4,    8,  16, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f2/e3 ", LAYER_CONV,   4,   4,    8,  16, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f3/s1 ", LAYER_CONV,   4,   4,   32,  16, 1, 0, 1), 0,  1, POOL_GLOBAL);

  net->num_weights = 3448;
  const char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);
  return net;
}
