// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "do_macc_macc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic do_macc_macc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic do_macc_macc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> do_macc_macc::ap_ST_pp0_stg0_fsm_0 = "1";
const sc_lv<5> do_macc_macc::ap_ST_pp0_stg1_fsm_1 = "10";
const sc_lv<5> do_macc_macc::ap_ST_pp0_stg2_fsm_2 = "100";
const sc_lv<5> do_macc_macc::ap_ST_pp0_stg3_fsm_3 = "1000";
const sc_lv<5> do_macc_macc::ap_ST_pp0_stg4_fsm_4 = "10000";
const sc_lv<32> do_macc_macc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> do_macc_macc::ap_const_lv1_1 = "1";
const sc_lv<32> do_macc_macc::ap_const_lv32_4 = "100";
const sc_lv<32> do_macc_macc::ap_const_lv32_1 = "1";
const sc_lv<32> do_macc_macc::ap_const_lv32_2 = "10";
const sc_lv<32> do_macc_macc::ap_const_lv32_3 = "11";
const sc_lv<64> do_macc_macc::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> do_macc_macc::ap_const_lv64_1 = "1";
const sc_lv<64> do_macc_macc::ap_const_lv64_2 = "10";
const sc_lv<64> do_macc_macc::ap_const_lv64_3 = "11";
const sc_lv<64> do_macc_macc::ap_const_lv64_4 = "100";
const sc_lv<64> do_macc_macc::ap_const_lv64_5 = "101";
const sc_lv<64> do_macc_macc::ap_const_lv64_6 = "110";
const sc_lv<64> do_macc_macc::ap_const_lv64_7 = "111";
const sc_lv<64> do_macc_macc::ap_const_lv64_8 = "1000";

do_macc_macc::do_macc_macc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1 = new do_macc_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("do_macc_fadd_32ns_32ns_32_5_full_dsp_U1");
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->clk(ap_clk);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->reset(ap_rst);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->din0(grp_fu_298_p0);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->din1(grp_fu_298_p1);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->ce(grp_fu_298_ce);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U1->dout(grp_fu_298_p2);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2 = new do_macc_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("do_macc_fadd_32ns_32ns_32_5_full_dsp_U2");
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->clk(ap_clk);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->reset(ap_rst);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->din0(grp_fu_303_p0);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->din1(grp_fu_303_p1);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->ce(grp_fu_303_ce);
    do_macc_fadd_32ns_32ns_32_5_full_dsp_U2->dout(grp_fu_303_p2);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3 = new do_macc_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("do_macc_fmul_32ns_32ns_32_4_max_dsp_U3");
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->clk(ap_clk);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->reset(ap_rst);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->din0(img_in_q0);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->din1(filt_in_q0);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->ce(grp_fu_307_ce);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U3->dout(grp_fu_307_p2);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4 = new do_macc_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("do_macc_fmul_32ns_32ns_32_4_max_dsp_U4");
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->clk(ap_clk);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->reset(ap_rst);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->din0(img_in_q1);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->din1(filt_in_q1);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->ce(grp_fu_314_ce);
    do_macc_fmul_32ns_32ns_32_4_max_dsp_U4->dout(grp_fu_314_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );

    SC_METHOD(thread_ap_reg_ppiten_pp0_it0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0_preg );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( grp_fu_298_p2 );

    SC_METHOD(thread_ap_sig_bdd_130);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_150);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_170);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_79);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_1);
    sensitive << ( ap_sig_bdd_130 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg2_fsm_2);
    sensitive << ( ap_sig_bdd_150 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg3_fsm_3);
    sensitive << ( ap_sig_bdd_170 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg4_fsm_4);
    sensitive << ( ap_sig_bdd_79 );

    SC_METHOD(thread_ap_sig_pprstidle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );

    SC_METHOD(thread_filt_in_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_filt_in_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_filt_in_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_filt_in_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_grp_fu_298_ce);

    SC_METHOD(thread_grp_fu_298_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( processing_element_products_reg_463 );
    sensitive << ( tmp_5_1_reg_553 );
    sensitive << ( tmp_5_3_reg_563 );
    sensitive << ( tmp_5_5_reg_573 );
    sensitive << ( tmp_5_7_reg_583 );

    SC_METHOD(thread_grp_fu_298_p1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3 );
    sensitive << ( ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5 );
    sensitive << ( ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7 );
    sensitive << ( ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9 );

    SC_METHOD(thread_grp_fu_303_ce);

    SC_METHOD(thread_grp_fu_303_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( tmp_s_reg_548 );
    sensitive << ( tmp_5_2_reg_558 );
    sensitive << ( tmp_5_4_reg_568 );
    sensitive << ( tmp_5_6_reg_578 );

    SC_METHOD(thread_grp_fu_303_p1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1 );
    sensitive << ( ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4 );
    sensitive << ( ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6 );
    sensitive << ( ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8 );

    SC_METHOD(thread_grp_fu_307_ce);

    SC_METHOD(thread_grp_fu_314_ce);

    SC_METHOD(thread_img_in_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_img_in_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_img_in_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_img_in_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_prod_out_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_prod_out_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );

    SC_METHOD(thread_prod_out_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_prod_out_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );

    SC_METHOD(thread_prod_out_d0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( grp_fu_307_p2 );
    sensitive << ( grp_fu_314_p2 );

    SC_METHOD(thread_prod_out_d1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( grp_fu_307_p2 );
    sensitive << ( grp_fu_314_p2 );

    SC_METHOD(thread_prod_out_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );

    SC_METHOD(thread_prod_out_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_sig_pprstidle_pp0 );

    ap_CS_fsm = "00001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0_preg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "do_macc_macc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, img_in_address0, "(port)img_in_address0");
    sc_trace(mVcdFile, img_in_ce0, "(port)img_in_ce0");
    sc_trace(mVcdFile, img_in_q0, "(port)img_in_q0");
    sc_trace(mVcdFile, img_in_address1, "(port)img_in_address1");
    sc_trace(mVcdFile, img_in_ce1, "(port)img_in_ce1");
    sc_trace(mVcdFile, img_in_q1, "(port)img_in_q1");
    sc_trace(mVcdFile, filt_in_address0, "(port)filt_in_address0");
    sc_trace(mVcdFile, filt_in_ce0, "(port)filt_in_ce0");
    sc_trace(mVcdFile, filt_in_q0, "(port)filt_in_q0");
    sc_trace(mVcdFile, filt_in_address1, "(port)filt_in_address1");
    sc_trace(mVcdFile, filt_in_ce1, "(port)filt_in_ce1");
    sc_trace(mVcdFile, filt_in_q1, "(port)filt_in_q1");
    sc_trace(mVcdFile, prod_out_address0, "(port)prod_out_address0");
    sc_trace(mVcdFile, prod_out_ce0, "(port)prod_out_ce0");
    sc_trace(mVcdFile, prod_out_we0, "(port)prod_out_we0");
    sc_trace(mVcdFile, prod_out_d0, "(port)prod_out_d0");
    sc_trace(mVcdFile, prod_out_address1, "(port)prod_out_address1");
    sc_trace(mVcdFile, prod_out_ce1, "(port)prod_out_ce1");
    sc_trace(mVcdFile, prod_out_we1, "(port)prod_out_we1");
    sc_trace(mVcdFile, prod_out_d1, "(port)prod_out_d1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_0, "ap_sig_cseq_ST_pp0_stg0_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg4_fsm_4, "ap_sig_cseq_ST_pp0_stg4_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_79, "ap_sig_bdd_79");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_1, "ap_sig_cseq_ST_pp0_stg1_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_130, "ap_sig_bdd_130");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg2_fsm_2, "ap_sig_cseq_ST_pp0_stg2_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_150, "ap_sig_bdd_150");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg3_fsm_3, "ap_sig_cseq_ST_pp0_stg3_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_170, "ap_sig_bdd_170");
    sc_trace(mVcdFile, grp_fu_307_p2, "grp_fu_307_p2");
    sc_trace(mVcdFile, processing_element_products_reg_463, "processing_element_products_reg_463");
    sc_trace(mVcdFile, grp_fu_314_p2, "grp_fu_314_p2");
    sc_trace(mVcdFile, processing_element_products_1_s_reg_468, "processing_element_products_1_s_reg_468");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1, "ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1");
    sc_trace(mVcdFile, processing_element_products_2_s_reg_503, "processing_element_products_2_s_reg_503");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2, "ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3, "ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3");
    sc_trace(mVcdFile, processing_element_products_3_s_reg_508, "processing_element_products_3_s_reg_508");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2, "ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3, "ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4, "ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4");
    sc_trace(mVcdFile, processing_element_products_4_s_reg_523, "processing_element_products_4_s_reg_523");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2, "ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3, "ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4, "ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5, "ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5");
    sc_trace(mVcdFile, processing_element_products_5_s_reg_528, "processing_element_products_5_s_reg_528");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2, "ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3, "ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4, "ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5, "ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6, "ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6");
    sc_trace(mVcdFile, processing_element_products_6_s_reg_533, "processing_element_products_6_s_reg_533");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7, "ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7");
    sc_trace(mVcdFile, processing_element_products_7_s_reg_538, "processing_element_products_7_s_reg_538");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8, "ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8");
    sc_trace(mVcdFile, processing_element_products_8_s_reg_543, "processing_element_products_8_s_reg_543");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9, "ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9");
    sc_trace(mVcdFile, grp_fu_298_p2, "grp_fu_298_p2");
    sc_trace(mVcdFile, tmp_s_reg_548, "tmp_s_reg_548");
    sc_trace(mVcdFile, grp_fu_303_p2, "grp_fu_303_p2");
    sc_trace(mVcdFile, tmp_5_1_reg_553, "tmp_5_1_reg_553");
    sc_trace(mVcdFile, tmp_5_2_reg_558, "tmp_5_2_reg_558");
    sc_trace(mVcdFile, tmp_5_3_reg_563, "tmp_5_3_reg_563");
    sc_trace(mVcdFile, tmp_5_4_reg_568, "tmp_5_4_reg_568");
    sc_trace(mVcdFile, tmp_5_5_reg_573, "tmp_5_5_reg_573");
    sc_trace(mVcdFile, tmp_5_6_reg_578, "tmp_5_6_reg_578");
    sc_trace(mVcdFile, tmp_5_7_reg_583, "tmp_5_7_reg_583");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0_preg, "ap_reg_ppiten_pp0_it0_preg");
    sc_trace(mVcdFile, grp_fu_298_p0, "grp_fu_298_p0");
    sc_trace(mVcdFile, grp_fu_298_p1, "grp_fu_298_p1");
    sc_trace(mVcdFile, grp_fu_303_p0, "grp_fu_303_p0");
    sc_trace(mVcdFile, grp_fu_303_p1, "grp_fu_303_p1");
    sc_trace(mVcdFile, grp_fu_298_ce, "grp_fu_298_ce");
    sc_trace(mVcdFile, grp_fu_303_ce, "grp_fu_303_ce");
    sc_trace(mVcdFile, grp_fu_307_ce, "grp_fu_307_ce");
    sc_trace(mVcdFile, grp_fu_314_ce, "grp_fu_314_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_pprstidle_pp0, "ap_sig_pprstidle_pp0");
#endif

    }
}

do_macc_macc::~do_macc_macc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete do_macc_fadd_32ns_32ns_32_5_full_dsp_U1;
    delete do_macc_fadd_32ns_32ns_32_5_full_dsp_U2;
    delete do_macc_fmul_32ns_32ns_32_4_max_dsp_U3;
    delete do_macc_fmul_32ns_32ns_32_4_max_dsp_U4;
}

void do_macc_macc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_pp0_stg0_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0_preg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_reg_ppiten_pp0_it0_preg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it1 = ap_reg_ppiten_pp0_it0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()) && 
             !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()))) {
            ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
        ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1 = processing_element_products_1_s_reg_468.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2 = processing_element_products_2_s_reg_503.read();
        ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3 = ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2 = processing_element_products_3_s_reg_508.read();
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3 = ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4 = ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2 = processing_element_products_4_s_reg_523.read();
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3 = ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4 = ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it3.read();
        ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5 = ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it4.read();
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2 = processing_element_products_5_s_reg_528.read();
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it3.read();
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it4.read();
        ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it5.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2 = processing_element_products_6_s_reg_533.read();
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it3.read();
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it4.read();
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it5.read();
        ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it6.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2 = processing_element_products_7_s_reg_538.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it3.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it4.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it5.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it6.read();
        ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it7.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2 = processing_element_products_8_s_reg_543.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it2.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it3.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it4.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it5.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it6.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it7.read();
        ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it8.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        processing_element_products_1_s_reg_468 = grp_fu_314_p2.read();
        processing_element_products_reg_463 = grp_fu_307_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        processing_element_products_2_s_reg_503 = grp_fu_307_p2.read();
        processing_element_products_3_s_reg_508 = grp_fu_314_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        processing_element_products_4_s_reg_523 = grp_fu_307_p2.read();
        processing_element_products_5_s_reg_528 = grp_fu_314_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        processing_element_products_6_s_reg_533 = grp_fu_307_p2.read();
        processing_element_products_7_s_reg_538 = grp_fu_314_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        processing_element_products_8_s_reg_543 = grp_fu_307_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        tmp_5_1_reg_553 = grp_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp_5_2_reg_558 = grp_fu_298_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp_5_3_reg_563 = grp_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        tmp_5_4_reg_568 = grp_fu_298_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        tmp_5_5_reg_573 = grp_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        tmp_5_6_reg_578 = grp_fu_298_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        tmp_5_7_reg_583 = grp_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        tmp_s_reg_548 = grp_fu_298_p2.read();
    }
}

void do_macc_macc::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it10.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_reg_ppiten_pp0_it0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
        ap_reg_ppiten_pp0_it0 = ap_start.read();
    } else {
        ap_reg_ppiten_pp0_it0 = ap_reg_ppiten_pp0_it0_preg.read();
    }
}

void do_macc_macc::thread_ap_return() {
    ap_return = grp_fu_298_p2.read();
}

void do_macc_macc::thread_ap_sig_bdd_130() {
    ap_sig_bdd_130 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void do_macc_macc::thread_ap_sig_bdd_150() {
    ap_sig_bdd_150 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void do_macc_macc::thread_ap_sig_bdd_170() {
    ap_sig_bdd_170 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void do_macc_macc::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void do_macc_macc::thread_ap_sig_bdd_79() {
    ap_sig_bdd_79 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void do_macc_macc::thread_ap_sig_cseq_ST_pp0_stg0_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_sig_cseq_ST_pp0_stg1_fsm_1() {
    if (ap_sig_bdd_130.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_sig_cseq_ST_pp0_stg2_fsm_2() {
    if (ap_sig_bdd_150.read()) {
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_sig_cseq_ST_pp0_stg3_fsm_3() {
    if (ap_sig_bdd_170.read()) {
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_sig_cseq_ST_pp0_stg4_fsm_4() {
    if (ap_sig_bdd_79.read()) {
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_sig_pprstidle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()))) {
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    } else {
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_filt_in_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            filt_in_address0 =  (sc_lv<4>) (ap_const_lv64_8);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            filt_in_address0 =  (sc_lv<4>) (ap_const_lv64_6);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            filt_in_address0 =  (sc_lv<4>) (ap_const_lv64_4);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            filt_in_address0 =  (sc_lv<4>) (ap_const_lv64_2);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            filt_in_address0 =  (sc_lv<4>) (ap_const_lv64_0);
        } else {
            filt_in_address0 = "XXXX";
        }
    } else {
        filt_in_address0 = "XXXX";
    }
}

void do_macc_macc::thread_filt_in_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            filt_in_address1 =  (sc_lv<4>) (ap_const_lv64_7);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            filt_in_address1 =  (sc_lv<4>) (ap_const_lv64_5);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            filt_in_address1 =  (sc_lv<4>) (ap_const_lv64_3);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            filt_in_address1 =  (sc_lv<4>) (ap_const_lv64_1);
        } else {
            filt_in_address1 = "XXXX";
        }
    } else {
        filt_in_address1 = "XXXX";
    }
}

void do_macc_macc::thread_filt_in_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        filt_in_ce0 = ap_const_logic_1;
    } else {
        filt_in_ce0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_filt_in_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        filt_in_ce1 = ap_const_logic_1;
    } else {
        filt_in_ce1 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_grp_fu_298_ce() {
    grp_fu_298_ce = ap_const_logic_1;
}

void do_macc_macc::thread_grp_fu_298_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        grp_fu_298_p0 = tmp_5_7_reg_583.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        grp_fu_298_p0 = tmp_5_5_reg_573.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        grp_fu_298_p0 = tmp_5_3_reg_563.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        grp_fu_298_p0 = tmp_5_1_reg_553.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        grp_fu_298_p0 = processing_element_products_reg_463.read();
    } else {
        grp_fu_298_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_grp_fu_298_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_8_s_reg_543_pp0_it9.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_6_s_reg_533_pp0_it7.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_4_s_reg_523_pp0_it5.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        grp_fu_298_p1 = ap_reg_ppstg_processing_element_products_2_s_reg_503_pp0_it3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        grp_fu_298_p1 = ap_const_lv32_0;
    } else {
        grp_fu_298_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_grp_fu_303_ce() {
    grp_fu_303_ce = ap_const_logic_1;
}

void do_macc_macc::thread_grp_fu_303_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        grp_fu_303_p0 = tmp_5_6_reg_578.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        grp_fu_303_p0 = tmp_5_4_reg_568.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        grp_fu_303_p0 = tmp_5_2_reg_558.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) {
        grp_fu_303_p0 = tmp_s_reg_548.read();
    } else {
        grp_fu_303_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_grp_fu_303_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_7_s_reg_538_pp0_it8.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_5_s_reg_528_pp0_it6.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_3_s_reg_508_pp0_it4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) {
        grp_fu_303_p1 = ap_reg_ppstg_processing_element_products_1_s_reg_468_pp0_it1.read();
    } else {
        grp_fu_303_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_grp_fu_307_ce() {
    grp_fu_307_ce = ap_const_logic_1;
}

void do_macc_macc::thread_grp_fu_314_ce() {
    grp_fu_314_ce = ap_const_logic_1;
}

void do_macc_macc::thread_img_in_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            img_in_address0 =  (sc_lv<4>) (ap_const_lv64_8);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            img_in_address0 =  (sc_lv<4>) (ap_const_lv64_6);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            img_in_address0 =  (sc_lv<4>) (ap_const_lv64_4);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            img_in_address0 =  (sc_lv<4>) (ap_const_lv64_2);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            img_in_address0 =  (sc_lv<4>) (ap_const_lv64_0);
        } else {
            img_in_address0 = "XXXX";
        }
    } else {
        img_in_address0 = "XXXX";
    }
}

void do_macc_macc::thread_img_in_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            img_in_address1 =  (sc_lv<4>) (ap_const_lv64_7);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            img_in_address1 =  (sc_lv<4>) (ap_const_lv64_5);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            img_in_address1 =  (sc_lv<4>) (ap_const_lv64_3);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            img_in_address1 =  (sc_lv<4>) (ap_const_lv64_1);
        } else {
            img_in_address1 = "XXXX";
        }
    } else {
        img_in_address1 = "XXXX";
    }
}

void do_macc_macc::thread_img_in_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        img_in_ce0 = ap_const_logic_1;
    } else {
        img_in_ce0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_img_in_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        img_in_ce1 = ap_const_logic_1;
    } else {
        img_in_ce1 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_prod_out_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read()))) {
        prod_out_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        prod_out_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        prod_out_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        prod_out_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        prod_out_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        prod_out_address0 = "XXXX";
    }
}

void do_macc_macc::thread_prod_out_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        prod_out_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        prod_out_address1 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        prod_out_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        prod_out_address1 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        prod_out_address1 = "XXXX";
    }
}

void do_macc_macc::thread_prod_out_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())))) {
        prod_out_ce0 = ap_const_logic_1;
    } else {
        prod_out_ce0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_prod_out_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())))) {
        prod_out_ce1 = ap_const_logic_1;
    } else {
        prod_out_ce1 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_prod_out_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())))) {
        prod_out_d0 = grp_fu_307_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        prod_out_d0 = grp_fu_314_p2.read();
    } else {
        prod_out_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_prod_out_d1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())))) {
        prod_out_d1 = grp_fu_314_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        prod_out_d1 = grp_fu_307_p2.read();
    } else {
        prod_out_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void do_macc_macc::thread_prod_out_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())))) {
        prod_out_we0 = ap_const_logic_1;
    } else {
        prod_out_we0 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_prod_out_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())))) {
        prod_out_we1 = ap_const_logic_1;
    } else {
        prod_out_we1 = ap_const_logic_0;
    }
}

void do_macc_macc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it3.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it4.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it5.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it6.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it7.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it8.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it9.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it10.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_3;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_pprstidle_pp0.read())) {
                ap_NS_fsm = ap_ST_pp0_stg4_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

